# Generated by Django 4.2 on 2023-05-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='cantidad',
            field=models.IntegerField(default=5, verbose_name='cantidad'),
            preserve_default=False,
        ),
    ]
