# Generated by Django 4.2 on 2023-05-02 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['-nombre'], 'verbose_name': ('Departamento',), 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('nombre', 'short_name')},
        ),
    ]
