# Generated by Django 4.2 on 2023-05-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_remove_empleado_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[(0, 'Contador'), (1, 'Administrador'), (2, 'Economista'), (3, 'Otro')], default=1, max_length=1, verbose_name='Trabajo'),
            preserve_default=False,
        ),
    ]
